services:
  usuario-service:
    image: sebastianhenaogamboa/usuario-service:latest
    container_name: usuario-service
    restart: unless-stopped
    depends_on:
      - db2
    ports:
      - "8086:8086"
      - "8087:8087"
    environment:
      - DB_USER=userdb
      - DB_PASS=passdb
      - JPA_DDL=create-drop
      - DB_HOST=jdbc:postgresql://db2:5432/curso_springboot
    networks:
      - mynetwork
  db2:
    image: postgres:latest
    container_name: db2
    restart: unless-stopped
    ports:
      - "5434:5434"
    environment:
      POSTGRES_DB: curso_springboot
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passdb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork
networks:
    mynetwork:
        driver: bridge